services:
  - type: web
    name: staging-test-render-web
    plan: free
    runtime: ruby
    buildCommand: bundle install
    startCommand: bin/rails s
    preDeployCommand: bin/rails db:migrate
    envVars:
      - key: RAILS_ENV
        value: staging

databases:
  - name: staging-test-render-postgres
    plan: free
    databaseName: test_render_staging
    user: test_render
