services:
  - type: web
    name: staging-test-render-web
    plan: free
    runtime: ruby
    buildCommand: bundle install
    startCommand: bin/rails s -e staging
    preDeployCommand: bin/rails db:migrate

databases:
  - name: staging-test-render-postgres
    plan: free
    databaseName: test_render_staging
    user: test_render
